import os
import sys
from pathlib import Path

# Ensure environment variables exist before other modules import config.
workspace = Path(__file__).resolve().parent.parent
os.environ.setdefault("MCP_REVIT_WORKSPACE_DIR", str(workspace))
os.environ.setdefault("MCP_REVIT_ALLOWED_DIRECTORIES", str(workspace))
os.environ.setdefault("MCP_REVIT_MODE", "mock")

# Add src folder to sys.path to allow imports
src_path = Path(__file__).resolve().parent.parent / "src"
sys.path.insert(0, str(src_path))

from revit_mcp_server.security.workspace import WorkspaceMonitor
from revit_mcp_server.jobs import JobManager
from revit_mcp_server.providers import (
    ProviderRegistry,
    RevitProvider,
    IfcProvider,
    AECMapperProvider,
    SQLiteExporterProvider,
    JobProvider,
    RhinoProvider,
    SemanticGraphProvider,
    SpeckleProvider,
    AutodeskDataProvider,
    NavisworksProvider,
    ApprovalProvider,
)

try:
    from revit_mcp_server.providers import McpProxyProvider
except ImportError:
    McpProxyProvider = None

def get_first_sentence(text: str) -> str:
    if not text:
        return ""
    text = text.strip().replace("\n", " ")
    parts = text.split(".")
    first = parts[0].strip()
    if first and not first.endswith("."):
        first += "."
    return first

def main():
    workspace = WorkspaceMonitor([])
    job_manager = JobManager()
    registry = ProviderRegistry()

    # List of all available providers in the system
    # We instantiate cloud providers with dummy keys to make sure they load their capabilities list
    provider_instances = []

    # Helper function to safely instantiate and add a provider
    def add_provider(name: str, inst_func):
        try:
            inst = inst_func()
            provider_instances.append((name, inst, None))
        except Exception as e:
            provider_instances.append((name, None, str(e)))

    add_provider("Approval", lambda: ApprovalProvider(workspace=workspace, registry=registry))
    add_provider("Revit", lambda: RevitProvider(workspace=workspace))
    add_provider("IFC", lambda: IfcProvider(workspace=workspace))
    add_provider("AEC Mapper", lambda: AECMapperProvider(workspace=workspace))
    add_provider("SQLite Exporter", lambda: SQLiteExporterProvider(workspace=workspace, registry=registry))
    add_provider("Job", lambda: JobProvider(manager=job_manager))
    add_provider("Rhino", lambda: RhinoProvider(workspace=workspace))
    add_provider("Navisworks", lambda: NavisworksProvider(workspace=workspace))
    add_provider("Semantic Graph", lambda: SemanticGraphProvider())
    add_provider("Speckle", lambda: SpeckleProvider(client_id="dummy"))
    add_provider("Autodesk Data", lambda: AutodeskDataProvider(client_id="dummy"))
    if McpProxyProvider:
        add_provider("Mcp Proxy", lambda: McpProxyProvider("https://localhost:9876/sse"))

    # Stably sort providers by name
    provider_instances.sort(key=lambda x: x[0].lower())

    output_lines = [
        "# Generated Tool Catalog",
        "",
        "<!-- This file is auto-generated by packages/mcp-server-revit/scripts/generate_tool_docs.py. Do not edit manually. -->",
        "",
        "This catalog lists all tools exposed by the AEC Model Bridge providers.",
        "",
        "> [!NOTE]",
        "> The columns `Mutating?` and `Execution Type` display the actual metadata parsed",
        "> from C# command specifications and provider capabilities.",
        ""
    ]

    for name, provider, error in provider_instances:
        output_lines.append(f"## {name} Provider")
        output_lines.append("")
        
        if error:
            output_lines.append(f"*Note: Not initialized in this environment ({error})*")
            output_lines.append("")
            continue
            
        tools = provider.get_capabilities()
        if not tools:
            output_lines.append("*No tools available for this provider.*")
            output_lines.append("")
            continue

        # Sort tools stably
        sorted_tools = sorted(tools, key=lambda t: t.name.lower())

        output_lines.append("| Tool Name | Description | Mutating? | Execution Type |")
        output_lines.append("| --- | --- | --- | --- |")
        for t in sorted_tools:
            desc = get_first_sentence(t.description)
            mutating_str = "Yes" if t.is_mutating else "No"
            exec_str = t.execution_mode
            output_lines.append(f"| `{t.name}` | {desc} | {mutating_str} | {exec_str} |")
        output_lines.append("")

    # Write output file
    repo_root = Path(__file__).resolve().parent.parent.parent.parent
    output_path = repo_root / "docs" / "tools-generated.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(output_lines) + "\n")

    print(f"Generated tool catalog successfully at {output_path}")

if __name__ == "__main__":
    main()
